notificationRetryJobCron: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * ? # every 5 minutes
#notificationRetryJobCron: 0 0/1 * 1/1 * ? * # retry every 1 mins
#notificationRetryJobCron: 0/20 * * * * ? # retry every 20 seconds

notifyUrl: https://api.notifications.service.gov.uk
notifyApiKey: 4108f2e8-7898-4284-a90e-6816883f29f6
notifyServiceId: f3d8fb42-a34b-4d85-8ac2-a62006a197dc
maxRetryCount: 3

templateIdMap:
    permissionsFinder:applicationReference: 09eb70ed-e5c7-4d28-87aa-553addfbcfc2 # applicationReference
    ogelRegistration:registrationComplete: 90389188-8587-4412-a973-b8e9bc67f7bd
    ogelRegistration:adminApprovalAccessRequest: 973eb1fb-cdc6-47db-a618-625d4e0e5e04
    ogelRegistration:adminApprovalRequired: 23c3e646-b621-4b39-9901-d0218e21d58d
    ogelRegistration:registrationApproved: 70499bb2-04b5-4955-8fc0-2e0a6cbbf12e
    ogelRegistration:registrationApprovedSiteChanged: 2c83b68f-04fd-4695-9370-aece6d793f70
    ogelRegistration:userAccountConfigured: e1a00f70-52dc-43fd-ae6c-eecb03c62bfe
    ogelRegistration:registrationDenied: 6e2ad997-c7d1-4fa2-8447-6fad997fefbb
    ogelRegistration:registrationBlacklisted: edbc68a0-1045-460e-a99b-67a5161f9054

templatePlaceholderMap:
    permissionsFinder:applicationReference:
    - applicationReference
    ogelRegistration:registrationComplete:
    - applicantName
    - spireUrl
    ogelRegistration:adminApprovalRequired:
    - applicantName
    - customerName
    ogelRegistration:adminApprovalAccessRequest:
    - adminName
    - fullName
    - userId
    - emailAddress
    - customerName
    - ogelType
    - viewSummaryUrl
    - adminApprovalUrl
    ogelRegistration:registrationApproved:
    - applicantName
    - customerName
    - adminName
    - viewLicenceUrl
    - spireUrl
    ogelRegistration:registrationApprovedSiteChanged:
    - applicantName
    - customerName
    - adminName
    - originalSite
    - newSite
    - viewLicenceUrl
    - spireUrl
    ogelRegistration:userAccountConfigured:
    - applicantName
    - customerName
    - permissionLevel
    - authorisedSites
    ogelRegistration:registrationDenied:
    - applicantName
    - customerName
    ogelRegistration:registrationBlacklisted:
    - applicantName
    - customerName

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8098

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: '[%d{HH:mm:ss.SSS}] [%-5level] [%class{0}:%method:%line] %msg %n'

database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:localNotification.db
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  initialSize: 1 # connections
  minSize: 1 # connections
  maxSize: 3 # connections
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

adminLogin: user
adminPassword: password