login: "${BASIC_AUTH_USER}"
password: "${BASIC_AUTH_PASSWORD}"

notifyUrl: "${NOTIFY_URL}"
notifyApiKey: "${NOTIFY_API_KEY}"

aws:
  credentials:
    accessKey: "${AWS_CREDENTIALS_ACCESS_KEY}"
    secretKey: "${AWS_CREDENTIALS_SECRET_KEY}"
  region: "${AWS_REGION}"
  sqsQueueUrl: "${AWS_SQS_QUEUE_URL}"
  sqsWaitTimeSeconds: ${AWS_SQS_WAIT_TIME_SECONDS}
  sqsRetryDelaySeconds: ${AWS_SQS_RETRY_DELAY_SECONDS}

server:
  type: simple
  connector:
    type: http
    port: ${PORT}
  applicationContextPath: /
  adminContextPath: /admin
  requestLog:
    appenders:
      - type: json-console-access

logging:
  level: INFO
  appenders:
    - type: json-console
