notificationRetryJobCron: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * ? # every 5 minutes

notifyUrl: https://api.notifications.service.gov.uk
notifyApiKey: 4108f2e8-7898-4284-a90e-6816883f29f6
notifyServiceId: f3d8fb42-a34b-4d85-8ac2-a62006a197dc
maxRetryCount: 3

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: INFO
  appenders:
      - type: console
        includeCallerData : true
        logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
  loggers:
     uk.gov.bis.lite.common.spire.client: TRACE

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=notificationsvc
  user: postgres
  password: password
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  initialSize: 1
  minSize: 1
  maxSize: 3
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

serviceLogin: service
servicePassword: password