login: user
password: pass

notifyUrl: https://api.notifications.service.gov.uk
notifyApiKey: notifyApiKey

aws:
  credentials:
    profileName: default
  region: eu-west-2
  sqsQueueUrl: sqsQueueUrl
  sqsWaitTimeSeconds: 20
  sqsRetryDelaySeconds: 60

server:
  type: simple
  connector:
    type: http
    port: 8080
  applicationContextPath: /
  adminContextPath: /admin
  requestLog:
    appenders:
      - type: console

logging:
  level: INFO
  appenders:
    - type: console
