notifyUrl: https://api.notifications.service.gov.uk
notifyApiKey: notifyApiKey

aws:
  credentials:
    profileName: default
  region: eu-west-2
  sqsQueueUrl: sqsQueueUrl
  sqsWaitTimeSeconds: 20
  sqsRetryDelaySeconds: 60

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: INFO
  appenders:
    - type: console
